name: sisters-salon-reservation-app
options:
  bundleIdPrefix: com.sisters.salon
  deploymentTarget:
    iOS: 13.0
fileGroups: [../../src]
configs:
  debug: debug
  release: release
settingGroups:
  app:
    base:
      PRODUCT_NAME: Sisters Salon
      PRODUCT_BUNDLE_IDENTIFIER: com.sisters.salon
      DEVELOPMENT_TEAM: W96LW7FRSD
targetTemplates:
  app:
    type: application
    sources:
      - path: Sources
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      groups: [app]
targets:
  sisters-salon-reservation-app_iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: sisters-salon-reservation-app_iOS
      - path: assets
        buildPhase: resources
        type: folder
      - path: LaunchScreen.storyboard
    info:
      path: sisters-salon-reservation-app_iOS/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [arm64, metal]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: "1.0.0"
    entitlements:
      path: sisters-salon-reservation-app_iOS/sisters-salon-reservation-app_iOS.entitlements
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      base:
        ENABLE_BITCODE: false
        ARCHS: [arm64]
        VALID_ARCHS: arm64 
        LIBRARY_SEARCH_PATHS[arch=x86_64]: $(inherited) $(PROJECT_DIR)/Externals/x86_64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        LIBRARY_SEARCH_PATHS[arch=arm64]: $(inherited) $(PROJECT_DIR)/Externals/arm64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64
      groups: [app]
    dependencies:
      - framework: libapp.a
        embed: false
      - sdk: CoreGraphics.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: QuartzCore.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - sdk: WebKit.framework
    preBuildScripts:
      - script: |
          set -e

          # nvm 환경 로드
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          # Homebrew 경로 추가
          export PATH="/opt/homebrew/bin:$PATH"

          # Rust/Cargo 경로 추가
          export PATH="$HOME/.cargo/bin:$PATH"

          # 프로젝트 루트로 이동
          cd "$SRCROOT/../.."

          # Frontend 빌드 (dist 폴더가 없거나 오래된 경우)
          if [ ! -d "../dist" ] || [ "../src" -nt "../dist" ]; then
            echo "Building frontend..."
            cd ..
            npm run build
            cd src-tauri
          fi

          # Rust 빌드
          echo "Building Rust code for iOS..."
          if [ "$CONFIGURATION" = "Release" ] || [ "$CONFIGURATION" = "release" ]; then
            cargo build --release --target aarch64-apple-ios --lib
            mkdir -p "$SRCROOT/Externals/arm64/release"
            cp "target/aarch64-apple-ios/release/libsisters_salon_reservation_app_lib.a" "$SRCROOT/Externals/arm64/release/libapp.a"
          else
            cargo build --target aarch64-apple-ios --lib
            mkdir -p "$SRCROOT/Externals/arm64/debug"
            cp "target/aarch64-apple-ios/debug/libsisters_salon_reservation_app_lib.a" "$SRCROOT/Externals/arm64/debug/libapp.a"
          fi

          echo "Rust build complete!"
        name: Build Rust Code
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(SRCROOT)/Externals/arm64/${CONFIGURATION}/libapp.a